insert into mst_detail_settings (setting_key, setting_value, setting_group, description) values
  ('site_title', 'Mikhail Daffa Herdiansah — Portfolio', 'content', 'Default portfolio setting for site_title'),
  ('meta_description', 'Portfolio of Mikhail Daffa Herdiansah — Full-Stack Developer Enthusiast and IT Student at Politeknik Astra.', 'content', 'Default portfolio setting for meta_description'),
  ('nav_brand', 'Mikhail', 'content', 'Default portfolio setting for nav_brand'),
  ('header_cta_label', 'GitHub', 'content', 'Default portfolio setting for header_cta_label'),
  ('header_cta_url', 'https://github.com/mikhaildh20', 'asset_or_link', 'Default portfolio setting for header_cta_url'),
  ('hero_badge', 'Full-Stack Developer Enthusiast · IT Student', 'content', 'Default portfolio setting for hero_badge'),
  ('hero_title', 'Turning my IT curiosity into practical web projects.', 'content', 'Default portfolio setting for hero_title'),
  ('hero_intro', 'Hello, I''m Mikhail Daffa Herdiansah, also known as Mike. I am an Informatics Management student at Politeknik Astra, class of 2023, with a strong passion for Information Technology and full-stack web development.', 'content', 'Default portfolio setting for hero_intro'),
  ('hero_primary_label', 'View my direction', 'content', 'Default portfolio setting for hero_primary_label'),
  ('hero_secondary_label', 'Preview CV', 'content', 'Default portfolio setting for hero_secondary_label'),
  ('hero_secondary_url', 'assets/curriculum_vitae.pdf', 'asset_or_link', 'Default portfolio setting for hero_secondary_url'),
  ('avatar_path', 'assets/avatar.jpg', 'asset_or_link', 'Default portfolio setting for avatar_path'),
  ('profile_asset_note', 'Place my photo at public/assets/avatar.jpg to replace this reserved profile image area.', 'content', 'Default portfolio setting for profile_asset_note'),
  ('about_title', 'I am building strong foundations in IT.', 'content', 'Default portfolio setting for about_title'),
  ('about_paragraph_1', 'I am an Informatics Management student at Politeknik Astra. My current LinkedIn positioning is Full-Stack Developer Enthusiast and IT Student.', 'content', 'Default portfolio setting for about_paragraph_1'),
  ('about_paragraph_2', 'I focus on learning how to build useful web-based systems, understand software development workflows, and improve through practical projects that can become real portfolio evidence.', 'content', 'Default portfolio setting for about_paragraph_2'),
  ('focus_title', 'The skill direction I am developing.', 'content', 'Default portfolio setting for focus_title'),
  ('focus_1_title', 'Frontend Development', 'content', 'Default portfolio setting for focus_1_title'),
  ('focus_1_body', 'I am learning to build clean interfaces with HTML, CSS, JavaScript, and responsive layout fundamentals.', 'content', 'Default portfolio setting for focus_1_body'),
  ('focus_2_title', 'Backend Development', 'content', 'Default portfolio setting for focus_2_title'),
  ('focus_2_body', 'I am developing my understanding of server-side logic, routing, APIs, data handling, and application structure.', 'content', 'Default portfolio setting for focus_2_body'),
  ('focus_3_title', 'Software Engineering', 'content', 'Default portfolio setting for focus_3_title'),
  ('focus_3_body', 'I want to improve how I plan, organize, document, version, and maintain software projects.', 'content', 'Default portfolio setting for focus_3_body'),
  ('focus_4_title', 'Information Technology', 'content', 'Default portfolio setting for focus_4_title'),
  ('focus_4_body', 'I am growing my technical literacy across systems, databases, development tools, and real-world IT workflows.', 'content', 'Default portfolio setting for focus_4_body'),
  ('work_title', 'I use this portfolio as a starting point for visible growth.', 'content', 'Default portfolio setting for work_title'),
  ('work_intro', 'This page is my personal landing page while I continue building public work, project case studies, and stronger development experience.', 'content', 'Default portfolio setting for work_intro'),
  ('work_detail_title', 'A professional base I can keep improving.', 'content', 'Default portfolio setting for work_detail_title'),
  ('work_detail_body', 'My goal is to present myself clearly, avoid overclaiming, and create a solid base that can grow as I add more repositories, project screenshots, CV updates, and professional milestones.', 'content', 'Default portfolio setting for work_detail_body'),
  ('tech_title', 'Tools and topics I am growing into.', 'content', 'Default portfolio setting for tech_title'),
  ('cv_title', 'Reserved space for my CV preview.', 'content', 'Default portfolio setting for cv_title'),
  ('cv_intro', 'I will place my CV file at public/assets/curriculum_vitae.pdf. Once the file is uploaded, this section will be ready for preview and download access.', 'content', 'Default portfolio setting for cv_intro'),
  ('cv_path', 'assets/curriculum_vitae.pdf', 'asset_or_link', 'Default portfolio setting for cv_path'),
  ('contact_title', 'Let''s connect and build from here.', 'content', 'Default portfolio setting for contact_title'),
  ('contact_body', 'I am open to learning opportunities, portfolio feedback, IT discussions, and collaboration around web development and software engineering.', 'content', 'Default portfolio setting for contact_body'),
  ('email', 'mikhaildaffa7@gmail.com', 'asset_or_link', 'Default portfolio setting for email'),
  ('github_url', 'https://github.com/mikhaildh20', 'asset_or_link', 'Default portfolio setting for github_url'),
  ('linkedin_url', 'https://www.linkedin.com/in/mikhaildhns', 'asset_or_link', 'Default portfolio setting for linkedin_url'),
  ('footer_tagline', 'Full-Stack Developer Enthusiast · IT Student', 'content', 'Default portfolio setting for footer_tagline')
on conflict (setting_key) do update set
  setting_value = excluded.setting_value,
  setting_group = excluded.setting_group,
  description = excluded.description,
  updated_at = now();
